-- Creator Analytics
-- Schedule proposal and approval foundation
-- File: Database/016_schedule_proposal_approval_queue.sql
--
-- Creates a read-only/dry-run scheduling proposal system.
-- It does NOT change anything in Buffer.
--
-- When scheduled Buffer posts exist and have synced into Supabase, the
-- refresh_schedule_proposals() function pairs them with the upcoming weekly
-- slots generated by migration 015.
--
-- Safe to rerun.

begin;

create extension if not exists pgcrypto;

create table if not exists public.schedule_change_proposals (
  id uuid primary key default gen_random_uuid(),

  buffer_post_id text not null unique,
  platform text not null,
  content_format text not null default 'short_form',

  post_text text,
  external_link text,

  current_due_at_utc timestamptz,
  current_due_at_local timestamp without time zone,

  proposed_due_at_utc timestamptz not null,
  proposed_due_at_local timestamp without time zone not null,

  slot_rank integer,
  source_recommendation_rank integer,
  recommendation_score numeric,
  confidence text,
  supporting_sample_size integer,
  metrics_status text,
  timezone_name text not null default 'America/Denver',

  approval_status text not null default 'Pending'
    check (
      approval_status in (
        'Pending',
        'Approved',
        'Rejected',
        'Applied',
        'Error'
      )
    ),

  approved_at timestamptz,
  rejected_at timestamptz,
  applied_at timestamptz,

  result_message text,
  error_message text,

  generated_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.schedule_change_proposals
  enable row level security;

create index if not exists
  schedule_change_proposals_status_idx
on public.schedule_change_proposals (approval_status);

create index if not exists
  schedule_change_proposals_proposed_time_idx
on public.schedule_change_proposals (proposed_due_at_utc);

create index if not exists
  schedule_change_proposals_platform_idx
on public.schedule_change_proposals (platform);

create or replace function public.refresh_schedule_proposals(
  p_start_date date default current_date,
  p_horizon_days integer default 21
)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_rows_changed integer := 0;
begin
  if p_horizon_days < 1 or p_horizon_days > 90 then
    raise exception 'p_horizon_days must be between 1 and 90';
  end if;

  with active_settings as (
    select
      platform,
      content_format,
      protected_hours,
      timezone_name
    from public.scheduling_cadence_settings
    where is_active = true
      and posts_per_week > 0
      and content_format = 'short_form'
  ),

  scheduled_posts as (
    select
      d.buffer_post_id,
      d.platform,
      'short_form'::text as content_format,
      d.post_text,
      d.external_link,
      d.published_at_utc as current_due_at_utc,
      d.published_at_local as current_due_at_local,

      row_number() over (
        partition by d.platform
        order by
          d.published_at_utc asc,
          d.buffer_post_id asc
      ) as post_sequence

    from public.looker_dashboard_posts d
    join active_settings s
      on s.platform = d.platform

    where d.status = 'scheduled'
      and d.published_at_utc is not null
      and d.published_at_utc >
        now() + make_interval(hours => s.protected_hours)
  ),

  calendar_dates as (
    select
      generate_series(
        p_start_date::timestamp,
        (p_start_date + p_horizon_days)::timestamp,
        interval '1 day'
      )::date as local_date
  ),

  future_slots as (
    select
      w.platform,
      w.content_format,
      w.slot_rank,
      w.source_recommendation_rank,
      w.publish_iso_day,
      w.publish_day_name,
      w.scheduled_time_local,
      w.recommendation_score,
      w.confidence,
      w.supporting_sample_size,
      w.metrics_status,
      w.timezone_name,

      c.local_date + w.scheduled_time_local
        as proposed_due_at_local,

      (
        c.local_date + w.scheduled_time_local
      ) at time zone w.timezone_name
        as proposed_due_at_utc,

      row_number() over (
        partition by w.platform
        order by
          c.local_date asc,
          w.scheduled_time_local asc,
          w.slot_rank asc
      ) as slot_sequence

    from public.looker_weekly_slot_plan w
    join calendar_dates c
      on extract(isodow from c.local_date)::integer =
         w.publish_iso_day
    join active_settings s
      on s.platform = w.platform
     and s.content_format = w.content_format

    where (
      c.local_date + w.scheduled_time_local
    ) at time zone w.timezone_name >
      now() + make_interval(hours => s.protected_hours)
  ),

  paired as (
    select
      p.buffer_post_id,
      p.platform,
      p.content_format,
      p.post_text,
      p.external_link,
      p.current_due_at_utc,
      p.current_due_at_local,

      s.proposed_due_at_utc,
      s.proposed_due_at_local,

      s.slot_rank,
      s.source_recommendation_rank,
      s.recommendation_score,
      s.confidence,
      s.supporting_sample_size,
      s.metrics_status,
      s.timezone_name

    from scheduled_posts p
    join future_slots s
      on s.platform = p.platform
     and s.slot_sequence = p.post_sequence
  )

  insert into public.schedule_change_proposals (
    buffer_post_id,
    platform,
    content_format,
    post_text,
    external_link,
    current_due_at_utc,
    current_due_at_local,
    proposed_due_at_utc,
    proposed_due_at_local,
    slot_rank,
    source_recommendation_rank,
    recommendation_score,
    confidence,
    supporting_sample_size,
    metrics_status,
    timezone_name,
    approval_status,
    generated_at,
    updated_at
  )
  select
    buffer_post_id,
    platform,
    content_format,
    post_text,
    external_link,
    current_due_at_utc,
    current_due_at_local,
    proposed_due_at_utc,
    proposed_due_at_local,
    slot_rank,
    source_recommendation_rank,
    recommendation_score,
    confidence,
    supporting_sample_size,
    metrics_status,
    timezone_name,
    'Pending',
    now(),
    now()
  from paired

  on conflict (buffer_post_id)
  do update set
    platform = excluded.platform,
    content_format = excluded.content_format,
    post_text = excluded.post_text,
    external_link = excluded.external_link,
    current_due_at_utc = excluded.current_due_at_utc,
    current_due_at_local = excluded.current_due_at_local,
    proposed_due_at_utc = excluded.proposed_due_at_utc,
    proposed_due_at_local = excluded.proposed_due_at_local,
    slot_rank = excluded.slot_rank,
    source_recommendation_rank =
      excluded.source_recommendation_rank,
    recommendation_score = excluded.recommendation_score,
    confidence = excluded.confidence,
    supporting_sample_size = excluded.supporting_sample_size,
    metrics_status = excluded.metrics_status,
    timezone_name = excluded.timezone_name,
    generated_at = now(),
    updated_at = now(),

    approval_status = case
      when public.schedule_change_proposals.approval_status
        in ('Applied', 'Error')
      then public.schedule_change_proposals.approval_status
      else 'Pending'
    end,

    approved_at = case
      when public.schedule_change_proposals.approval_status
        in ('Applied', 'Error')
      then public.schedule_change_proposals.approved_at
      else null
    end,

    rejected_at = case
      when public.schedule_change_proposals.approval_status
        in ('Applied', 'Error')
      then public.schedule_change_proposals.rejected_at
      else null
    end

  where public.schedule_change_proposals.approval_status
    not in ('Applied');

  get diagnostics v_rows_changed = row_count;

  return v_rows_changed;
end;
$$;

create or replace function public.set_schedule_proposal_decision(
  p_proposal_id uuid,
  p_decision text
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_normalized_decision text;
begin
  v_normalized_decision := initcap(lower(trim(p_decision)));

  if v_normalized_decision not in (
    'Pending',
    'Approved',
    'Rejected'
  ) then
    raise exception
      'Decision must be Pending, Approved, or Rejected';
  end if;

  update public.schedule_change_proposals
  set
    approval_status = v_normalized_decision,

    approved_at = case
      when v_normalized_decision = 'Approved'
      then now()
      else null
    end,

    rejected_at = case
      when v_normalized_decision = 'Rejected'
      then now()
      else null
    end,

    error_message = null,
    updated_at = now()

  where id = p_proposal_id
    and approval_status not in ('Applied');

  return found;
end;
$$;

create or replace view public.looker_schedule_change_proposals
with (security_invoker = false)
as
select
  id as proposal_id,
  buffer_post_id,
  platform,
  content_format,
  post_text,
  external_link,

  current_due_at_utc,
  current_due_at_local,

  proposed_due_at_utc,
  proposed_due_at_local,

  trim(to_char(
    proposed_due_at_local,
    'FMDay, FMMonth DD at FMHH12:MI AM'
  )) as proposed_schedule_label,

  slot_rank,
  source_recommendation_rank,
  recommendation_score,
  confidence,
  supporting_sample_size,
  metrics_status,
  timezone_name,

  approval_status,
  approved_at,
  rejected_at,
  applied_at,

  result_message,
  error_message,
  generated_at,
  updated_at

from public.schedule_change_proposals;

revoke all on public.schedule_change_proposals
  from public, anon, authenticated;

revoke all on function public.refresh_schedule_proposals(date, integer)
  from public, anon, authenticated;

revoke all on function public.set_schedule_proposal_decision(uuid, text)
  from public, anon, authenticated;

revoke all on public.looker_schedule_change_proposals
  from public, anon, authenticated;

grant execute on function public.refresh_schedule_proposals(date, integer)
  to service_role;

grant execute on function public.set_schedule_proposal_decision(uuid, text)
  to service_role;

grant select on public.looker_schedule_change_proposals
  to creator_dashboard_reader;

commit;
