import type {
  AnalyticsData,
  DashboardData,
  LabelQueueData,
  ScheduleApprovalsData,
  SystemStatusData,
  UpcomingPostsData,
} from "@/data/models";

export const dashboardFixture: DashboardData = {
  summary: {
    postCount: 2,
    totalViews: 15_400,
    totalReactions: 1_000,
    totalComments: 30,
    totalShares: 15,
    averageViews: 7_700,
    averageInteractionRate: 6.25,
  },
  filterablePosts: [
    {
      key: "SANITIZED_POST_ONE",
      platform: "tiktok",
      channelName: "sample-channel",
      caption: "A sanitized gameplay moment with a surprising ending",
      externalLink: "https://example.invalid/posts/sample-one",
      publishedAt: "2026-08-27T20:00:00.000Z",
      publishDay: "Thursday",
      publishHour: 14,
      labelStatus: "labeled",
      clipGroup: "Sample Clip Alpha",
      game: "Sample Game",
      contentType: "Highlight",
      vibe: "Chaotic",
      views: 9_200,
      reactions: 700,
      comments: 20,
      shares: 10,
      saves: 5,
      interactionRate: 8,
    },
    {
      key: "SANITIZED_POST_TWO",
      platform: "youtube",
      channelName: "sample-channel",
      caption: "A second sanitized highlight for test coverage",
      externalLink: null,
      publishedAt: "2026-08-26T19:00:00.000Z",
      publishDay: "Wednesday",
      publishHour: 13,
      labelStatus: "unlabeled",
      clipGroup: null,
      game: null,
      contentType: null,
      vibe: null,
      views: 6_200,
      reactions: 300,
      comments: 10,
      shares: 5,
      saves: 5,
      interactionRate: 4.5,
    },
  ],
  recentPosts: [
    {
      platform: "tiktok",
      channelName: "sample-channel",
      caption: "A sanitized gameplay moment with a surprising ending",
      externalLink: "https://example.invalid/posts/sample-one",
      publishedAt: "2026-08-27T20:00:00.000Z",
      labelStatus: "labeled",
      clipGroup: "Sample Clip Alpha",
      views: 9_200,
      interactions: 735,
    },
    {
      platform: "youtube",
      channelName: "sample-channel",
      caption: "A second sanitized highlight for test coverage",
      externalLink: null,
      publishedAt: "2026-08-26T19:00:00.000Z",
      labelStatus: "unlabeled",
      clipGroup: null,
      views: 6_200,
      interactions: 320,
    },
  ],
  growth: [
    { platform: "tiktok", capturedOn: "2026-08-28", viewsGained: 2_400 },
    { platform: "youtube", capturedOn: "2026-08-28", viewsGained: 1_100 },
  ],
  topTimes: [
    {
      platform: "tiktok",
      day: "Monday",
      hour: 14,
      postCount: 8,
      averageViews: 8_400,
    },
  ],
  topContent: [
    {
      platform: "tiktok",
      game: "Sample Game",
      contentType: "Highlight",
      vibe: "Chaotic",
      postCount: 5,
      averageViews: 8_900,
    },
  ],
  latestMetricDate: "2026-08-28",
  partialErrors: [],
};

export const upcomingPostsFixture: UpcomingPostsData = {
  posts: [
    {
      key: "SANITIZED_POST_A",
      platform: "tiktok",
      channelName: "Sample TikTok Channel",
      caption: "A sanitized scheduled caption for a gameplay clip",
      externalLink: "https://example.invalid/posts/scheduled-one",
      dueAt: "2026-08-31T20:00:00.000Z",
      labelStatus: "labeled",
      clipGroup: "Sample Clip Beta",
      game: "Sample Game",
      contentType: "Highlight",
      lastSyncedAt: "2026-08-29T15:00:00.000Z",
      proposal: {
        status: "Pending",
        proposedDueAt: "2026-09-01T01:30:00.000Z",
        confidence: "Moderate",
        metricsStatus: "Fresh",
      },
    },
    {
      key: "SANITIZED_POST_B",
      platform: "youtube",
      channelName: "Sample YouTube Channel",
      caption: "Another sanitized scheduled caption",
      externalLink: null,
      dueAt: "2026-09-01T18:00:00.000Z",
      labelStatus: "unlabeled",
      clipGroup: null,
      game: null,
      contentType: null,
      lastSyncedAt: null,
      proposal: null,
    },
  ],
  partialErrors: [],
};

export const labelQueueFixture: LabelQueueData = {
  summary: {
    unlinked: 2,
    pendingExport: 1,
    exportedStillUnlinked: 1,
  },
  items: [
    {
      platform: "tiktok",
      channelName: "Sample TikTok Channel",
      sourceStatus: "sent",
      caption: "A sanitized unlabeled clip awaiting export",
      externalLink: "https://example.invalid/posts/queue-one",
      publishedAtLocal: "2026-08-28T14:00:00",
      views: 4_200,
      latestMetricDate: "2026-08-29",
      queueState: "pending_export",
    },
    {
      platform: "youtube",
      channelName: "Sample YouTube Channel",
      sourceStatus: "sent",
      caption: "A sanitized exported clip that remains unlinked",
      externalLink: null,
      publishedAtLocal: "2026-08-27T13:30:00",
      views: 1_800,
      latestMetricDate: "2026-08-29",
      queueState: "exported_unlinked",
    },
  ],
  clipGroups: [
    {
      name: "Sample Shared Clip",
      game: "Sample Game",
      contentType: "Highlight",
      platforms: ["tiktok", "youtube"],
      postCount: 2,
      recentPosts: [
        {
          platform: "tiktok",
          caption: "A sanitized linked TikTok post",
          externalLink: null,
          publishedAt: "2026-08-26T20:00:00.000Z",
        },
      ],
    },
  ],
  partialErrors: [],
};

const baseProposal: ScheduleApprovalsData["proposals"][number] = {
  platform: "tiktok",
  contentFormat: "short_form",
  caption: "A sanitized schedule proposal",
  externalLink: "https://example.invalid/posts/proposal-one",
  currentDueAt: "2026-09-01T01:30:00.000Z",
  proposedDueAt: "2026-09-01T20:00:00.000Z",
  approvalStatus: "Pending",
  applicationState: "pending",
  confidence: "Moderate",
  metricsStatus: "Fresh",
  timezoneName: "America/Denver",
  recommendationScore: 0.82,
  recommendationRank: 1,
  slotRank: 2,
  supportingSampleSize: 18,
  generatedAt: "2026-08-29T09:10:00.000Z",
  updatedAt: "2026-08-29T09:10:00.000Z",
  approvedAt: null,
  appliedAt: null,
  exportState: "pending_export",
  lastSyncedAt: "2026-08-29T09:00:00.000Z",
  blockingReasons: [],
};

export const scheduleApprovalsFixture: ScheduleApprovalsData = {
  proposals: [
    baseProposal,
    {
      ...baseProposal,
      caption: "A sanitized approved proposal ready for Make",
      approvalStatus: "Approved",
      applicationState: "ready_for_make",
      approvedAt: "2026-08-29T10:00:00.000Z",
      exportState: "not_observable",
    },
    {
      ...baseProposal,
      caption: "A sanitized approved proposal blocked at preflight",
      approvalStatus: "Approved",
      applicationState: "approved_blocked",
      approvedAt: "2026-08-29T10:05:00.000Z",
      blockingReasons: [
        "Blocked: current schedule changed after proposal generation",
      ],
    },
    {
      ...baseProposal,
      caption: "A sanitized applied proposal awaiting synchronization",
      approvalStatus: "Applied",
      applicationState: "applied_awaiting_sync",
      appliedAt: "2026-08-29T10:10:00.000Z",
    },
    {
      ...baseProposal,
      caption: "A sanitized applied and synchronized proposal",
      approvalStatus: "Applied",
      applicationState: "synchronized",
      appliedAt: "2026-08-29T10:15:00.000Z",
      lastSyncedAt: "2026-08-29T10:30:00.000Z",
    },
    {
      ...baseProposal,
      caption: "A sanitized proposal with an application error",
      approvalStatus: "Error",
      applicationState: "error",
    },
  ],
  partialErrors: [],
};

export const analyticsFixture: AnalyticsData = {
  contentPerformance: [
    {
      platform: "tiktok",
      game: "Sample Game",
      contentType: "Highlight",
      vibe: "Chaotic",
      hookType: "Cold open",
      postCount: 12,
      averageViews: 8_400,
      medianViews: 7_900,
      averageInteractionRate: 6.2,
    },
    {
      platform: "youtube",
      game: "Sample Game",
      contentType: "Short",
      vibe: "Focused",
      hookType: null,
      postCount: 3,
      averageViews: 2_100,
      medianViews: 1_900,
      averageInteractionRate: 4.1,
    },
  ],
  postingWindows: [
    {
      platform: "tiktok",
      channelName: "Sample TikTok Channel",
      day: "Monday",
      hour: 14,
      postCount: 8,
      averageViews: 8_800,
      medianViews: 8_100,
      averageInteractionRate: 6.5,
    },
    {
      platform: "youtube",
      channelName: "Sample YouTube Channel",
      day: "Wednesday",
      hour: 18,
      postCount: 3,
      averageViews: 2_200,
      medianViews: 2_000,
      averageInteractionRate: 4.2,
    },
  ],
  recommendations: [
    {
      platform: "tiktok",
      rank: 1,
      recommendedSlot: "Monday · 2 PM–6 PM",
      sampleSize: 8,
      platformSampleSize: 48,
      averageViews: 8_800,
      medianViews: 8_100,
      score: 0.88,
      confidence: "Medium",
      latestMetricDate: "2026-08-28",
      metricsAgeDays: 1,
      metricsStatus: "Fresh",
      readyForApprovalMode: true,
    },
    {
      platform: "youtube",
      rank: 1,
      recommendedSlot: "Wednesday · 6 PM–10 PM",
      sampleSize: 3,
      platformSampleSize: 14,
      averageViews: 2_200,
      medianViews: 2_000,
      score: 0.61,
      confidence: "Experimental",
      latestMetricDate: "2026-08-24",
      metricsAgeDays: 5,
      metricsStatus: "Stale",
      readyForApprovalMode: false,
    },
  ],
  fallbackSelections: [
    {
      platform: "tiktok",
      game: "Sample Game",
      contentType: "Highlight",
      vibe: "Chaotic",
      selectedModelLevel: "Game + Content Type",
      selectedModelPriority: 3,
      groupSampleSize: 14,
      minimumSampleSize: 12,
      recommendedSlot: "Monday · 2 PM–6 PM",
      score: 0.8,
      confidence: "High",
      metricsStatus: "Fresh",
      readyForPreview: true,
      fallbackReason:
        "More specific groups were too small; used Game + Content Type",
    },
  ],
  cadenceSettings: [
    {
      platform: "tiktok",
      contentFormat: "short_form",
      postsPerWeek: 5,
      maxPostsPerDay: 2,
      minGapHours: 4,
      protectedHours: 24,
      minimumSampleSize: 12,
      metricsFreshnessLimitDays: 4,
      timezoneName: "America/Denver",
      isActive: true,
      updatedAt: "2026-08-28T20:00:00.000Z",
    },
    {
      platform: "youtube",
      contentFormat: "short_form",
      postsPerWeek: 3,
      maxPostsPerDay: 1,
      minGapHours: 6,
      protectedHours: 24,
      minimumSampleSize: 12,
      metricsFreshnessLimitDays: 4,
      timezoneName: "America/Denver",
      isActive: true,
      updatedAt: "2026-08-28T20:00:00.000Z",
    },
  ],
  weeklySlots: [
    {
      platform: "tiktok",
      contentFormat: "short_form",
      slotRank: 1,
      day: "Monday",
      hour: 14,
      localTime: "14:00:00",
      recommendedWindow: "2 PM–6 PM",
      score: 0.88,
      confidence: "Medium",
      sampleSize: 8,
      metricsStatus: "Fresh",
      timezoneName: "America/Denver",
    },
    {
      platform: "youtube",
      contentFormat: "short_form",
      slotRank: 1,
      day: "Wednesday",
      hour: 18,
      localTime: "18:00:00",
      recommendedWindow: "6 PM–10 PM",
      score: 0.61,
      confidence: "Experimental",
      sampleSize: 3,
      metricsStatus: "Stale",
      timezoneName: "America/Denver",
    },
  ],
  partialErrors: [],
};

export const systemStatusFixture: SystemStatusData = {
  thresholds: { postSyncStaleHours: 15, metricsStaleHours: 48 },
  summary: {
    observedPosts: 14,
    postSyncPlatformsNeedingAttention: 1,
    observedSentMetrics: 10,
    metricsPlatformsNeedingAttention: 1,
    proposalErrors: 1,
    blockedApprovedProposals: 2,
    unlinkedPosts: 5,
    pendingLabelExports: 2,
    exportedStillUnlinked: 3,
  },
  postSyncFreshness: [
    {
      platform: "tiktok",
      state: "Fresh",
      observedPosts: 8,
      recordsWithTimestamp: 8,
      historicalRowsOutsideThreshold: 7,
      missingTimestamps: 0,
      latestSyncedAt: "2026-08-29T16:00:00.000Z",
    },
    {
      platform: "youtube",
      state: "Missing",
      observedPosts: 6,
      recordsWithTimestamp: 0,
      historicalRowsOutsideThreshold: 0,
      missingTimestamps: 6,
      latestSyncedAt: null,
    },
  ],
  metricsFreshness: [
    {
      platform: "tiktok",
      state: "Fresh",
      observedSentPosts: 6,
      recordsWithTimestamp: 6,
      historicalRowsOutsideThreshold: 5,
      missingTimestamps: 0,
      latestCapturedAt: "2026-08-29T15:00:00.000Z",
    },
    {
      platform: "youtube",
      state: "Stale",
      observedSentPosts: 4,
      recordsWithTimestamp: 4,
      historicalRowsOutsideThreshold: 4,
      missingTimestamps: 0,
      latestCapturedAt: "2026-08-26T14:00:00.000Z",
    },
  ],
  cadenceSettings: analyticsFixture.cadenceSettings,
  previewReadiness: [
    {
      platform: "tiktok",
      previewRows: 6,
      readyRows: 4,
      blockedRows: 2,
      activeProposalBlocks: 1,
      contentSpecificRows: 4,
      platformFallbackRows: 2,
      guardrailPassRows: 5,
      firstProposedAtLocal: "2026-08-31T14:00:00",
      lastProposedAtLocal: "2026-09-06T18:00:00",
      sameChannelBlocks: 1,
      channelIdentityBlocks: 0,
      configurationBlocks: 0,
      dailyCapacityBlocks: 0,
      weeklyCapacityBlocks: 0,
    },
  ],
  blockedReasons: [
    { reason: "Blocked: same-channel minimum-gap conflict", count: 2 },
  ],
  recentProposalErrors: [
    { platform: "tiktok", updatedAt: "2026-08-29T15:00:00.000Z" },
  ],
  automationTelemetry: {
    available: false,
    explanation:
      "The repository defines automation_runs but contains no writer for it. External health is unavailable.",
  },
  partialErrors: [],
};
